### ISSUE TITLE
Struggling to recreate your experience w/ ReadDir

### ISSUE THREAD

**Issue by initialed85** [KablamoOSS/gofilewalk#1]
Hi team,

I hope everyone is doing well.

I sat down to try and write The Next Big Thing In Syncing Files For Developers and quickly came unstuck finding a reliable library to do file watch event for macOS so I found myself wondering "how slow can it really be to just walk the folder to be sync at a regular rate?"

Heaps slow, as I found out, so after lots of searching I landed upon the blog post that refers to this repo.

My test case was the monorepo I work in- it's 26GB (has some envs and whatnot in there too at the moment) and it's about 500,000-odd files.

Here's my output:

```
$ go build -o bin/syncer cmd/syncer/main.go && bin/syncer -send -localPath ~/Projects/FTP/ims-mono -remotePath scratch/remote -remoteHost localhost
2022/07/10 05:09:47 500638 files in 5.432810501s <-- this is github.com/MichaelTJones/walk; absolutely smashes the CPU because goroutines
2022/07/10 05:10:09 500637 files in 21.849600317s <-- this is recursive os.ReadDir w/ string args
2022/07/10 05:10:30 500637 files in 21.596501124s <-- this is recursive file.ReadDir (like in this repo)
```

The code I was using is at https://github.com/initialed85/syncer; please forgive the WIP nature of it, any structure fell to pieces when I started having to hack my way around fsnotify problems and then work out walk performance issues.

So I figure either I'm doing something wrong, or the directory structure that this repo was testing against has some peculiarities that favour ReadDir.

Any ideas?

**Comment by boyter** [comment]
Hey @initialed85 

Glad to see someone else discovering that walking the file system is a lot slower than you expect it to be.

I am unaware of any reason that ReadDir should be slower in this case, other than perhaps a regression slipped into a later version of Go? What version are you running on? This was run on Go 1.17. It also does depend on what you are walking though, and the OS you are running things on and the file system. Windows for example can be very slow when it comes to lots of small files.

I actually have a Python script designed to test the edge cases of these sort of things https://github.com/boyter/scc/blob/master/examples/performance_tests/create_folders_with_files.py which you might want to try. Its possible that you are hitting some sort of situation that favours more Goroutines, which is why you are seeing the parallel walk work better. 

There is also this https://github.com/dbaggerman/cuba which is something I used in scc. It allows goroutines to be the producers of their own work, which can be useful when doing file walks allowing you to control how many spin up.

Id suggest trying the above Python script and see which one works best for you.

**Comment by initialed85** [comment]
Hey @boyter thx for the reply.

I'm running macOS Monterey, Go version is `go1.18.2 darwin/amd64`.

I'll do some testing with the structure your Python script creates and see what I find.

The only thing I can I think is the nature of the file size- I've got quite a few massive files containing test data (huge chunks of JSON, SNMP walks etc)- perhaps `os.Stat` against those is slow or something.

https://github.com/dbaggerman/cuba looks cool, seems like a good way to limit concurrency, probably necessary for what I'm trying achieve, I assume at a certain point more concurrency only makes things worse for trying to optimise throughput when syscalls are involved.

Thanks again!

EDIT: I'll close this issue btw- not really an issue

**Comment by boyter** [comment]
@initialed85 That helps.

I think os.Stat shouldn't be slow for anything, but not 100% sure on that. I suspect its mostly limited by the filesystem than anything else though.

You are right though, at some point concurrency makes it worse, although I usually run into ulimit issues before then, at least in my tests.

Please to let me know how it goes for you! Having another data point is always helpful with this.
